# ENMAX values from VASP-recommended PBE_54 POTCARs (eV)
# Used for dynamic ENCUT calculation: ENCUT = max(ENMAX) * multiplier
# Reference: POTCAR header lines in PBE_54 dataset

H: 250.0
He: 479.0
Li: 499.0
Be: 309.0
B: 318.7
C: 400.0
N: 400.0
O: 400.0
F: 400.0
Ne: 344.0
Na: 260.0
Mg: 200.0
Al: 240.3
Si: 245.3
P: 255.0
S: 280.0
Cl: 262.0
Ar: 266.0
K: 259.0
Ca: 267.0
Sc: 223.0
Ti: 495.0
V: 476.0
Cr: 227.0
Mn: 270.0
Fe: 267.9
Co: 268.0
Ni: 270.0
Cu: 295.4
Zn: 277.0
Ga: 135.0
Ge: 174.0
As: 209.0
Se: 212.0
Br: 213.0
Rb: 220.0
Sr: 229.0
Y: 203.0
Zr: 230.0
Nb: 209.0
Mo: 225.0
Ru: 213.0
Rh: 229.0
Pd: 251.0
Ag: 250.0
Cd: 274.0
In: 96.0
Sn: 103.0
Sb: 172.0
Te: 175.0
I: 176.0
Cs: 220.0
Ba: 238.0
Hf: 220.0
Ta: 224.0
W: 224.0
Re: 226.0
Os: 228.0
Ir: 211.0
Pt: 230.0
Au: 230.0
La: 219.0
Ce: 273.0
Gd: 256.0
U: 253.0
