# Metallic elements for pure metal detection
# Used for automatic ISMEAR=1, SIGMA=0.1 (Methfessel-Paxton) setting

elements:
  - Li
  - Be
  - Na
  - Mg
  - Al
  - K
  - Ca
  - Sc
  - Ti
  - V
  - Cr
  - Mn
  - Fe
  - Co
  - Ni
  - Cu
  - Zn
  - Ga
  - Rb
  - Sr
  - Y
  - Zr
  - Nb
  - Mo
  - Tc
  - Ru
  - Rh
  - Pd
  - Ag
  - Cd
  - In
  - Sn
  - Cs
  - Ba
  - Hf
  - Ta
  - W
  - Re
  - Os
  - Ir
  - Pt
  - Au
  - La
  - Ce
  - Pr
  - Nd
  - Sm
  - Eu
  - Gd
  - Tb
  - Dy
  - Ho
  - Er
  - Tm
  - Yb
  - Lu
  - U
  - Np
  - Pu
