# VASP PAW PBE pseudopotentials â€” official recommended variants
# Reference: https://www.vasp.at/wiki/index.php/Available_PAW_potentials
# Dataset: PBE_54 (Issue E: explicit version metadata)

potcar_version: "54"

vasp_recommended:
  # Main group
  H: "H"
  He: "He"
  Li: "Li_sv"
  Be: "Be"
  B: "B"
  C: "C"
  N: "N"
  O: "O"
  F: "F"
  Ne: "Ne"
  Na: "Na_pv"
  Mg: "Mg"
  Al: "Al"
  Si: "Si"
  P: "P"
  S: "S"
  Cl: "Cl"
  Ar: "Ar"
  K: "K_sv"
  Ca: "Ca_sv"
  # 3d transition metals
  Sc: "Sc_sv"
  Ti: "Ti_sv"
  V: "V_sv"
  Cr: "Cr_pv"
  Mn: "Mn_pv"
  Fe: "Fe_pv"
  Co: "Co"
  Ni: "Ni"
  Cu: "Cu"
  Zn: "Zn"
  # p-block row 4
  Ga: "Ga_d"
  Ge: "Ge_d"
  As: "As"
  Se: "Se"
  Br: "Br"
  Kr: "Kr"
  # 4d transition metals
  Rb: "Rb_sv"
  Sr: "Sr_sv"
  Y: "Y_sv"
  Zr: "Zr_sv"
  Nb: "Nb_sv"
  Mo: "Mo_sv"
  Tc: "Tc_pv"
  Ru: "Ru_pv"
  Rh: "Rh_pv"
  Pd: "Pd"
  Ag: "Ag"
  Cd: "Cd"
  # p-block row 5
  In: "In_d"
  Sn: "Sn_d"
  Sb: "Sb"
  Te: "Te"
  I: "I"
  Xe: "Xe"
  # 5d transition metals
  Cs: "Cs_sv"
  Ba: "Ba_sv"
  Hf: "Hf_pv"
  Ta: "Ta_pv"
  W: "W_sv"
  Re: "Re"
  Os: "Os"
  Ir: "Ir"
  Pt: "Pt"
  Au: "Au"
  Hg: "Hg"
  # p-block row 6
  Tl: "Tl_d"
  Pb: "Pb_d"
  Bi: "Bi_d"
  # Lanthanides
  La: "La"
  Ce: "Ce"
  Pr: "Pr_3"
  Nd: "Nd_3"
  Sm: "Sm_3"
  Eu: "Eu_2"
  Gd: "Gd_3"
  Tb: "Tb_3"
  Dy: "Dy_3"
  Ho: "Ho_3"
  Er: "Er_3"
  Tm: "Tm_3"
  Yb: "Yb_2"
  Lu: "Lu_3"
  # Actinides
  U: "U"
  Np: "Np"
  Pu: "Pu"

# MP default POTCAR variants (subset where they differ from VASP recommended)
mp_default_overrides:
  Fe: "Fe_pv"
  Ti: "Ti_pv"
  V: "V_pv"
  Mo: "Mo_pv"
  W: "W_pv"
  Cr: "Cr_pv"
  Mn: "Mn_pv"
